services:
  - type: web
    name: matematikportal-api
    rootDir: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: matematikportal-db
          property: connectionString
      - key: FRONTEND_ORIGIN
        value: https://matematikportal-frontend.onrender.com

  - type: static
    name: matematikportal-frontend
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: frontend

databases:
  - name: matematikportal-db
